service:
  name: PCFApplication
  identifier: PCFApplication
  orgIdentifier: my_org
  projectIdentifier: my_project
  tags:
    PCF_Deployment: "true"   # mirrors uDeploy tag

  serviceDefinition:
    type: TAS
    spec:
      manifests:
        - manifest:
            identifier: tas_manifest
            type: TasManifest
            spec:
              store:
                type: Inline
                spec:
                  content: |
                    applications:
                      - name: <+service.variables.ApplicationName>
                        memory: 512M
                        instances: 1
                        env:
                          NAMESPACE: <+service.variables.Namespace>

  variables:
    - name: ApplicationName          # from template/ApplicationName
      type: String
      value: ""
    - name: Namespace                # from template/Namespace
      type: String
      value: "value1"
